# Generated by Django 5.2.9 on 2026-01-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image'), ('VIDEO', 'Video'), ('LINK', 'Link'), ('MIXED', 'Mixed')], default='TEXT', max_length=20),
        ),
    ]
